import {
  Cohort,
  CoworkZone,
  TeamMember,
  Ticket,
  Application,
  IntakeWindow,
  MentorshipSession,
  MenteePortfolioItem,
  BmsCanvas,
  BmsMilestone,
  BmsKpis,
  BmsDocument,
} from '@tdgh/types';

export const SEED_COWORK_ZONES: CoworkZone[] = [
  {
    id: 'zone-hotdesks',
    slug: 'hot-desks-commons',
    name: 'Flex Hot Desks (Commons)',
    floor: 1,
    capacity: 24,
    svgCoordinates: 'M 40,50 L 260,50 L 260,180 L 40,180 Z',
    colorToken: '#2563EB',
    status: 'AVAILABLE',
    amenities: ['1 Gbps Fiber Wi-Fi', 'USB-C / AC Power Ports', 'Filtered Water & Barista Coffee', 'Locker Access'],
    hourlyRateZar: 45,
    dailyRateZar: 180,
    monthlyRateZar: 1850,
    specs: {
      powerOutlets: 28,
      hasBackboneWifi: true,
      hasAvDisplay: false,
      ergonomicChairs: 24,
      naturalLight: true,
    },
    description: 'High-energy shared communal workspace overlooking Scottsville main concourse. Ideal for freelancers, remote tech workers, and early-stage tinkerers.',
    photoGallery: [
      'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    id: 'zone-dedicated',
    slug: 'dedicated-desks-pod',
    name: 'Dedicated Founder Desks',
    floor: 1,
    capacity: 12,
    svgCoordinates: 'M 280,50 L 520,50 L 520,180 L 280,180 Z',
    colorToken: '#06B6D4',
    status: 'AVAILABLE',
    amenities: ['Reserved Desk & Keycard', 'Dual 27" 4K Monitor Arm', 'Dedicated Under-Desk Pedestal', 'Priority Meeting Credits'],
    hourlyRateZar: 70,
    dailyRateZar: 280,
    monthlyRateZar: 3200,
    specs: {
      powerOutlets: 16,
      hasBackboneWifi: true,
      hasAvDisplay: true,
      ergonomicChairs: 12,
      naturalLight: true,
    },
    description: 'Permanent workstation reserved exclusively for venture founders and senior engineers building sustained products.',
    photoGallery: [
      'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    id: 'zone-boardroom',
    slug: 'impact-boardroom',
    name: 'Executive Impact Boardroom',
    floor: 1,
    capacity: 14,
    svgCoordinates: 'M 540,50 L 760,50 L 760,200 L 540,200 Z',
    colorToken: '#F59E0B',
    status: 'AVAILABLE',
    amenities: ['75" 4K UltraHD Video Bar', 'Acoustic Soundproofing', 'Conference 360 Mic', 'Smart Whiteboard'],
    hourlyRateZar: 350,
    dailyRateZar: 2200,
    monthlyRateZar: 14000,
    specs: {
      powerOutlets: 12,
      hasBackboneWifi: true,
      hasAvDisplay: true,
      ergonomicChairs: 14,
      naturalLight: true,
    },
    description: 'Flagship boardroom engineered for funder presentations, corporate stakeholder summits, and seed-round investor pitches.',
    photoGallery: [
      'https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    id: 'zone-codinglab',
    slug: 'codetrepreneurs-lab',
    name: 'Codetrepreneurs Dev Arena',
    floor: 1,
    capacity: 20,
    svgCoordinates: 'M 40,200 L 340,200 L 340,380 L 40,380 Z',
    colorToken: '#10B981',
    status: 'AVAILABLE',
    amenities: ['Linux Dual-Boot Desktops', 'Subnet Testing Router', 'Git Deployment Wall Display', 'Peer Pair-Programming Desks'],
    hourlyRateZar: 60,
    dailyRateZar: 240,
    monthlyRateZar: 2600,
    specs: {
      powerOutlets: 24,
      hasBackboneWifi: true,
      hasAvDisplay: true,
      ergonomicChairs: 20,
      naturalLight: false,
    },
    description: 'High-throughput software development laboratory home to TDGH 1-Year Codetrepreneurs fellowship.',
    photoGallery: [
      'https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    id: 'zone-booths',
    slug: 'focus-phone-booths',
    name: 'Acoustic Meeting Pods',
    floor: 1,
    capacity: 4,
    svgCoordinates: 'M 360,200 L 520,200 L 520,290 L 360,290 Z',
    colorToken: '#8B5CF6',
    status: 'AVAILABLE',
    amenities: ['Acoustic Felt Insulation', 'Dimmable Ring Light', 'Quiet Fan Ventilation', 'Integrated Desk'],
    hourlyRateZar: 90,
    dailyRateZar: 450,
    monthlyRateZar: 4200,
    specs: {
      powerOutlets: 4,
      hasBackboneWifi: true,
      hasAvDisplay: false,
      ergonomicChairs: 4,
      naturalLight: false,
    },
    description: 'Private 1-on-1 soundproof pods designed for investor calls, customer interviews, and podcast recordings.',
    photoGallery: [
      'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    id: 'zone-makerspace',
    slug: '3d-additive-makerspace',
    name: '3D Additive Studio & FabLab',
    floor: 1,
    capacity: 10,
    svgCoordinates: 'M 360,310 L 520,310 L 520,380 L 360,380 Z',
    colorToken: '#EF4444',
    status: 'AVAILABLE',
    amenities: ['Prusa & Bambu Lab FDM Printers', 'Resin SLA Wash & Cure Station', 'Fume Extractor Hoods', 'Digital Calipers & Soldering Bench'],
    hourlyRateZar: 120,
    dailyRateZar: 600,
    monthlyRateZar: 4800,
    specs: {
      powerOutlets: 16,
      hasBackboneWifi: true,
      hasAvDisplay: true,
      ergonomicChairs: 10,
      naturalLight: true,
    },
    description: 'Industrial rapid prototyping laboratory enabling rapid physical casing creation, prosthetics fabrication, and precision parts design.',
    photoGallery: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1200&q=80',
    ],
  },
  {
    id: 'zone-cafe',
    slug: 'daily-grind-kitchen',
    name: 'Community Hub Cafe & Kitchen',
    floor: 1,
    capacity: 30,
    svgCoordinates: 'M 540,220 L 760,220 L 760,380 L 540,380 Z',
    colorToken: '#64748B',
    status: 'AVAILABLE',
    amenities: ['Espresso Machine', 'Microwaves & Refrigerators', 'High-top Gathering Tables', 'Community Notice Wall'],
    hourlyRateZar: 0,
    dailyRateZar: 0,
    monthlyRateZar: 0,
    specs: {
      powerOutlets: 10,
      hasBackboneWifi: true,
      hasAvDisplay: false,
      ergonomicChairs: 20,
      naturalLight: true,
    },
    description: 'The social heartbeat of TDGH. Where coders, makers, and local community elders cross-pollinate ideas over fresh coffee.',
    photoGallery: [
      'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
    ],
  },
];

export const SEED_COHORTS: Cohort[] = [
  {
    id: 'cohort-code-2025',
    year: '2025',
    track: 'CODETREPRENEURS',
    title: 'Codetrepreneurs Fellowship 2025',
    summary: 'Full-time 12-month immersion: Next.js, PostgreSQL, Distributed APIs, Lean Startup validation, and venture pitching in Cape Town tech ecosystem.',
    startDate: '2025-02-01',
    endDate: '2025-11-30',
    status: 'ACTIVE',
    membersCount: 22,
    members: [
      {
        id: 'mem-1',
        name: 'Sipho Ndlovu',
        suburb: 'Scottsville, Kraaifontein',
        track: 'CODETREPRENEURS',
        bio: 'Former retail assistant turned full-stack developer. Built KasiPay, an offline-first QR payments app for spaza shops.',
        avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
        capstoneTitle: 'KasiPay Mobile POS',
        employedOrLaunched: true,
        githubUrl: 'https://github.com',
      },
      {
        id: 'mem-2',
        name: 'Chantel Adams',
        suburb: 'Bloekombos, Kraaifontein',
        track: 'CODETREPRENEURS',
        bio: 'Self-taught UI/UX designer and frontend engineer specializing in low-bandwidth React web portals.',
        avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80',
        capstoneTitle: 'CivicAlert Kraaifontein',
        employedOrLaunched: true,
        linkedinUrl: 'https://linkedin.com',
      },
      {
        id: 'mem-3',
        name: 'Darren Van Wyk',
        suburb: 'Peerless Park, Kraaifontein',
        track: 'CODETREPRENEURS',
        bio: 'Passionate about cloud systems, containerization, and municipal logistics optimization.',
        avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
        capstoneTitle: 'FleetRoute CapeTown',
        employedOrLaunched: true,
      },
    ],
    capstones: [
      {
        id: 'cap-kasipay',
        title: 'KasiPay — Spaza Financial OS',
        tagline: 'Empowering township micro-retailers with zero-fee QR settlement and tap-to-phone card processing.',
        description: 'Built with Next.js 15, Supabase, and WebUSB thermal printing. Processes over 400 daily transactions in Scottsville pilot.',
        creators: ['Sipho Ndlovu', 'Zukiswa Mthembu'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1556742049-0a67e557224f?auto=format&fit=crop&w=800&q=80',
        demoUrl: 'https://kasipay.dailygrindhub.co.za',
        repoUrl: 'https://github.com/tdgh/kasipay',
        tags: ['Next.js', 'FinTech', 'Township Economy', 'Offline-First'],
        featured: true,
      },
      {
        id: 'cap-civicalert',
        title: 'CivicAlert SA',
        tagline: 'Hyperlocal municipal fault tracking and community safety escalation grid for Kraaifontein.',
        description: 'Direct integration with municipal water & electrical ticket dispatch via WhatsApp API and geospatial tagging.',
        creators: ['Chantel Adams', 'Keanu Jacobs'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=800&q=80',
        demoUrl: 'https://civicalert.dailygrindhub.co.za',
        repoUrl: 'https://github.com/tdgh/civic-alert',
        tags: ['CivicTech', 'Geospatial', 'WhatsApp Cloud API'],
        featured: true,
      },
    ],
  },
  {
    id: 'cohort-3d-2025',
    year: '2025',
    track: '3D_PRINTING',
    title: 'Additive Manufacturing & Prototyping 2025',
    summary: '6-month intensive diploma covering SolidWorks CAD design, slicing tolerances, FDM/SLA maintenance, and small-batch sustainable production.',
    startDate: '2025-03-01',
    endDate: '2025-08-31',
    status: 'ACTIVE',
    membersCount: 16,
    members: [
      {
        id: 'mem-3d-1',
        name: 'Anathi Gxilishe',
        suburb: 'Scottsville, Kraaifontein',
        track: '3D_PRINTING',
        bio: 'CAD specialist focusing on recycled PET filament extrusion and prosthetic assist devices.',
        avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
        capstoneTitle: 'ReFilament Extruder Pro',
        employedOrLaunched: true,
      },
      {
        id: 'mem-3d-2',
        name: 'Mignon September',
        suburb: 'Scottsdene, Kraaifontein',
        track: '3D_PRINTING',
        bio: 'Industrial product designer crafting ergonomic drone chassis and agricultural sensors for local urban farms.',
        avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
        capstoneTitle: 'AgriPod Modular Sensor Casing',
        employedOrLaunched: true,
      },
    ],
    capstones: [
      {
        id: 'cap-agripod',
        title: 'AgriPod Sensor Housing',
        tagline: 'IP67 weather-resistant 3D printed sensor enclosures manufactured using locally recycled plastics.',
        description: 'Designed in Fusion 360 and printed in PETG. Deployed across 15 agricultural micro-tunnels in Philippi and Kraaifontein.',
        creators: ['Mignon September', 'Anathi Gxilishe'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
        cadFileUrl: '/models/agripod-v2.stl',
        tags: ['Additive Manufacturing', 'AgriTech', 'Circular Economy', 'CAD'],
        featured: true,
      },
    ],
  },
  {
    id: 'cohort-code-2024',
    year: '2024',
    track: 'CODETREPRENEURS',
    title: 'Codetrepreneurs Inaugural Fellowship 2024',
    summary: 'Our founding cohort of 18 students from Kraaifontein, achieving an 89% graduation rate into employment and incubated startups.',
    startDate: '2024-01-15',
    endDate: '2024-11-15',
    status: 'COMPLETED',
    membersCount: 18,
    members: [],
    capstones: [
      {
        id: 'cap-kasifuel',
        title: 'KasiFuel Last-Mile Gas',
        tagline: 'Smart LPG cylinder exchange and telemetry for suburban townships.',
        description: 'Graduated into the TDGH 10-Week Pre-Incubation accelerator and secured angel grant funding.',
        creators: ['Lwando Cele', 'Peter Hendricks'],
        thumbnailUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
        tags: ['IoT', 'Logistics', 'Clean Energy'],
        featured: false,
      },
    ],
  },
];

export const SEED_TEAM: TeamMember[] = [
  {
    id: 'team-1',
    name: 'Kurt Minnaar',
    role: 'Executive Hub Director & Founder',
    bio: 'Pioneering community social entrepreneur and educator passionate about catalytic youth development in Kraaifontein.',
    department: 'INCUBATION',
    avatarUrl: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
    order: 1,
    email: 'kurt@dailygrindhub.co.za',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'team-2',
    name: 'Ntsika Mokoena',
    role: 'Head of Software Engineering & Mentorship',
    bio: 'Former senior fintech architect leading the 12-month Codetrepreneurs fellowship and technical syllabus.',
    department: 'CODETREPRENEURS',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=400&q=80',
    order: 2,
    email: 'ntsika@dailygrindhub.co.za',
    linkedin: 'https://linkedin.com',
  },
  {
    id: 'team-3',
    name: 'Liesl Brink',
    role: 'Additive Manufacturing & FabLab Lead',
    bio: 'Mechanical engineer and 3D printing specialist driving localized product prototyping and circular plastics recycling.',
    department: 'MAKER_3D',
    avatarUrl: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=400&q=80',
    order: 3,
    email: 'liesl@dailygrindhub.co.za',
  },
  {
    id: 'team-4',
    name: 'Tariq Johnson',
    role: 'Incubator Venture Manager',
    bio: 'Venture mentor advising accepted incubatees on Lean canvas modeling, regulatory compliance, and seed fundraising.',
    department: 'INCUBATION',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80',
    order: 4,
    email: 'tariq@dailygrindhub.co.za',
  },
  {
    id: 'team-5',
    name: 'Nomsa Sithole',
    role: 'Community Operations & Coworking Lead',
    bio: 'Managing member experience, facility bookings, events hosting, and multi-department support ticket triage.',
    department: 'COWORKING',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=400&q=80',
    order: 5,
    email: 'nomsa@dailygrindhub.co.za',
  },
];

export const SEED_TICKETS: Ticket[] = [
  {
    id: 'tkt-101',
    ticketNumber: 'TDG-2025-084',
    subject: 'Boardroom booking inquiry for Kraaifontein Youth Tech Summit',
    description: 'We would like to reserve the Impact Boardroom for 14 people on Friday from 09:00 to 14:00. Will require 4K display and dual microphones.',
    department: 'COWORKING',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    submittedByName: 'Farouk Petersen',
    submittedByEmail: 'farouk@capeyouthtrust.org.za',
    submittedByPhone: '+27 82 555 1294',
    assignedToName: 'Nomsa Sithole',
    createdAt: '2025-09-14T08:30:00Z',
    updatedAt: '2025-09-15T11:20:00Z',
    messages: [
      {
        id: 'msg-1',
        ticketId: 'tkt-101',
        senderId: 'user-ext-1',
        senderName: 'Farouk Petersen',
        senderRole: 'GUEST',
        isInternalNote: false,
        content: 'Hi TDGH team, looking forward to hosting our regional youth workshop. Please confirm catering policy and AV setup.',
        createdAt: '2025-09-14T08:30:00Z',
      },
      {
        id: 'msg-2',
        ticketId: 'tkt-101',
        senderId: 'team-5',
        senderName: 'Nomsa Sithole',
        senderRole: 'DEPARTMENT_STAFF',
        isInternalNote: false,
        content: 'Hi Farouk! The Impact Boardroom is available on Friday. Our 75" 4K screen and 360 mic are ready for plug-and-play. External tea/coffee setup is included.',
        createdAt: '2025-09-15T11:20:00Z',
      },
    ],
  },
  {
    id: 'tkt-102',
    ticketNumber: 'TDG-2025-088',
    subject: 'Application follow-up: Codetrepreneurs 2026 Batch',
    description: 'Submitted my portfolio and GitHub links last week. Wanted to confirm if my aptitude test booking link was received.',
    department: 'CODETREPRENEURS',
    status: 'OPEN',
    priority: 'NORMAL',
    submittedByName: 'Zinhle Khumalo',
    submittedByEmail: 'zinhle.k@gmail.com',
    submittedByPhone: '+27 71 884 9912',
    createdAt: '2025-09-15T14:10:00Z',
    updatedAt: '2025-09-15T14:10:00Z',
    messages: [
      {
        id: 'msg-3',
        ticketId: 'tkt-102',
        senderId: 'user-ext-2',
        senderName: 'Zinhle Khumalo',
        senderRole: 'APPLICANT',
        isInternalNote: false,
        content: 'Good day, please confirm if my Git repository was received correctly for the 2026 intake review.',
        createdAt: '2025-09-15T14:10:00Z',
      },
    ],
  },
  {
    id: 'tkt-103',
    ticketNumber: 'TDG-2025-091',
    subject: 'CAD Tolerances & Custom TPU Filament Sourcing',
    description: 'We are prototyping an orthopedic sole insert and need guidance on nozzle diameter settings and TPU 95A shore hardness print beds.',
    department: 'MAKER_3D',
    status: 'OPEN',
    priority: 'URGENT',
    submittedByName: 'Llewellyn Cupido',
    submittedByEmail: 'llewellyn@kasi-ortho.co.za',
    createdAt: '2025-09-15T16:45:00Z',
    updatedAt: '2025-09-15T16:45:00Z',
    messages: [],
  },
];

export const SEED_INTAKE_WINDOWS: IntakeWindow[] = [
  {
    track: 'CODETREPRENEURS',
    title: 'Codetrepreneurs Fellowship 2026',
    isOpen: true,
    deadlineDate: '2026-11-30',
    capacityLimit: 48,
    statusNotice: '2026 Fellowship Intake Active — Round 1 Applications Open',
  },
  {
    track: 'MAKER_3D',
    title: '3D Printing & Additive FabLab Studio',
    isOpen: false,
    nextOpenDate: '2027-02-15',
    capacityLimit: 16,
    statusNotice: 'Intake Closed — Priority Waitlist Active (Re-opens 15 Feb 2027)',
  },
  {
    track: 'INCUBATION',
    title: 'Pre-Incubation Venture BMS Cohort',
    isOpen: true,
    deadlineDate: '2026-12-15',
    capacityLimit: 10,
    statusNotice: 'Quarterly Venture Intake Open — Reviewing Cohort 4',
  },
  {
    track: 'COWORKING',
    title: 'Community Co-Working Desks & Pods',
    isOpen: true,
    capacityLimit: 60,
    statusNotice: 'Year-Round Hot Desks & Dedicated Pods Active',
  },
];

export const SEED_APPLICATIONS: Application[] = [
  {
    id: 'app-501',
    fullName: 'Kaylin Fortuin',
    email: 'kaylin.f@outlook.com',
    phone: '+27 74 123 9988',
    suburb: 'Scottsville, Kraaifontein',
    track: 'CODETREPRENEURS',
    stage: 'IN_REVIEW',
    submittedAt: '2025-09-12T10:00:00Z',
    updatedAt: '2025-09-14T15:30:00Z',
    payload: {
      motivation: 'I want to build software solutions that solve youth unemployment in Kraaifontein. I taught myself HTML/CSS at the local library and want to master full-stack production.',
      educationLevel: 'Matric Certificate (with Math & Physical Science)',
      priorExperience: 'Built static landing page for uncle auto workshop using Tailwind CSS.',
      githubOrPortfolioUrl: 'https://github.com/kaylin-f',
    },
    scores: [
      {
        motivation: 9,
        technicalAptitude: 8,
        feasibility: 9,
        notes: 'High grit, outstanding self-study trajectory. Strong candidate for 2026 coding intake.',
        reviewerId: 'team-2',
        updatedAt: '2025-09-14T15:30:00Z',
      },
    ],
    verificationStatus: {
      idDocumentVerified: true,
      proofOfAddressVerified: true,
      academicRecordVerified: false,
      complianceOrPitchVerified: false,
      verifiedByStaffId: 'team-admin',
      verifiedAt: '2025-09-13T11:00:00Z',
      auditNotes: 'SAPS-certified RSA ID and Scottsville municipal water bill verified. Awaiting Matric certificate re-upload.',
    },
  },
  {
    id: 'app-502',
    fullName: 'Simphiwe Mavuso',
    email: 'simphiwe@greenwaste.org.za',
    phone: '+27 83 499 1102',
    suburb: 'Bloekombos, Kraaifontein',
    track: 'MAKER_3D',
    stage: 'INTERVIEW_SCHEDULED',
    submittedAt: '2025-09-10T14:20:00Z',
    updatedAt: '2025-09-13T09:00:00Z',
    interviewDate: '2025-09-18T10:30:00Z',
    payload: {
      motivation: 'Our project shreds local plastic waste into 3D printer filament. We need the FabLab equipment to refine our heated extrusion nozzle.',
      educationLevel: 'TVET College Mechanical N4',
      priorExperience: '2 years working with lathe, milling, and basic Cura 3D slicing.',
    },
    verificationStatus: {
      idDocumentVerified: true,
      proofOfAddressVerified: true,
      academicRecordVerified: true,
      complianceOrPitchVerified: true,
      verifiedByStaffId: 'team-admin',
      verifiedAt: '2025-09-12T16:00:00Z',
      auditNotes: 'TVET certification and Bloekombos ward councillor proof of residency verified.',
    },
  },
  {
    id: 'app-503',
    fullName: 'Bianca Meyer',
    email: 'bianca@kraai-delivery.co.za',
    phone: '+27 81 294 8831',
    suburb: 'Peerless Park North',
    track: 'INCUBATION',
    stage: 'ACCEPTED',
    submittedAt: '2025-09-10T09:15:00Z',
    updatedAt: '2025-09-12T14:00:00Z',
    assignedMentorId: 'team-1',
    assignedMentorName: 'Kurt Minnaar',
    payload: {
      motivation: 'Electric bicycle courier network for local pharmacies delivering chronic medication to elderly residents in Scottsville and Scottsdene.',
      businessConcept: 'Kraai-Med Delivery & Logistics',
      pitchDeckUrl: 'https://storage.tdgh.co.za/decks/kraai-med-2025.pdf',
    },
    verificationStatus: {
      idDocumentVerified: true,
      proofOfAddressVerified: true,
      academicRecordVerified: true,
      complianceOrPitchVerified: true,
      verifiedByStaffId: 'team-admin',
      verifiedAt: '2025-09-11T10:00:00Z',
      auditNotes: 'Verified municipal lease and business plan. High impact community healthcare logistics.',
    },
  },
  {
    id: 'app-504',
    fullName: 'Sipho Ndlovu',
    email: 'sipho@kasipay.co.za',
    phone: '+27 82 301 4455',
    suburb: 'Scottsville, Kraaifontein',
    track: 'INCUBATION',
    stage: 'ACCEPTED',
    submittedAt: '2025-08-20T08:00:00Z',
    updatedAt: '2025-09-01T10:00:00Z',
    assignedMentorId: 'team-4',
    assignedMentorName: 'Tariq Johnson',
    payload: {
      motivation: 'Scaling KasiPay payment terminal to 200 spaza retailers across Kraaifontein.',
      businessConcept: 'KasiPay Financial Technologies',
      pitchDeckUrl: 'https://storage.tdgh.co.za/decks/kasipay-pitch.pdf',
    },
    scores: [
      {
        motivation: 10,
        technicalAptitude: 9,
        feasibility: 10,
        notes: 'Exceptional traction and clear community impact. Accepted into Cohort 4.',
        reviewerId: 'team-admin',
        updatedAt: '2025-09-01T10:00:00Z',
      },
    ],
    verificationStatus: {
      idDocumentVerified: true,
      proofOfAddressVerified: true,
      academicRecordVerified: true,
      complianceOrPitchVerified: true,
      verifiedByStaffId: 'team-admin',
      verifiedAt: '2025-08-25T14:00:00Z',
      auditNotes: 'Full CIPC incorporation (2024/889201/07), SARS Tax PIN, and FICA verification confirmed.',
    },
  },
  {
    id: 'app-505',
    fullName: 'Luvuyo Jantjies',
    email: 'luvuyo.j@gmail.com',
    phone: '+27 76 892 1144',
    suburb: 'Wallacedene, Kraaifontein',
    track: 'MAKER_3D',
    stage: 'WAITLISTED',
    submittedAt: '2025-09-14T11:20:00Z',
    updatedAt: '2025-09-14T11:20:00Z',
    payload: {
      motivation: 'I design custom prosthetic limb brackets and assistive devices using recycled PET plastics. I want to commercialize this through the FabLab.',
      educationLevel: 'Matric Certificate',
      priorExperience: 'Completed open-source Blender and 3D modeling workshops.',
    },
    verificationStatus: {
      idDocumentVerified: true,
      proofOfAddressVerified: true,
      academicRecordVerified: false,
      complianceOrPitchVerified: false,
      verifiedByStaffId: 'team-admin',
      verifiedAt: '2025-09-14T15:00:00Z',
      auditNotes: 'Dossier saved to priority waitlist. Ready for immediate fast-tracking upon Feb 2027 intake opening.',
    },
  },
];

export const SEED_MENTORSHIP_SESSIONS: MentorshipSession[] = [
  {
    id: 'ses-101',
    mentorId: 'team-4',
    mentorName: 'Tariq Johnson',
    menteeId: 'app-504',
    menteeName: 'Sipho Ndlovu',
    ventureName: 'KasiPay Financial Technologies',
    sessionDate: '2025-09-12T14:00:00Z',
    topic: 'BMS Canvas Value Proposition & Offline QR Terminal Testing',
    feedbackNotes: 'Reviewed merchant acquisition metrics in Scottsville. 45 spaza shops active on pilot. Recommended finalizing CIPC MOI and submitting B-BBEE Level 1 affidavit.',
    actionItems: [
      'Upload CIPC registration certificate to BMS Vault',
      'Test thermal Bluetooth receipt printing with 5 merchant pilot',
      'Draft Month 2 burn runway projection',
    ],
    nextMeetingDate: '2025-09-19T14:00:00Z',
    status: 'COMPLETED',
    createdAt: '2025-09-12T15:00:00Z',
  },
  {
    id: 'ses-102',
    mentorId: 'team-4',
    mentorName: 'Tariq Johnson',
    menteeId: 'app-504',
    menteeName: 'Sipho Ndlovu',
    ventureName: 'KasiPay Financial Technologies',
    sessionDate: '2025-09-19T14:00:00Z',
    topic: 'Sprint 3 Deliverable Review: Banking Switch Rails & Compliance',
    feedbackNotes: 'Scheduled review of Stitch EFT integration agreements. Verified SARB compliance outline.',
    actionItems: [
      'Submit banking confirmation letter to document vault',
      'Complete Week 5–6 sprint roadmap items',
    ],
    nextMeetingDate: '2025-09-26T14:00:00Z',
    status: 'SCHEDULED',
    createdAt: '2025-09-15T09:00:00Z',
  },
  {
    id: 'ses-103',
    mentorId: 'team-1',
    mentorName: 'Kurt Minnaar',
    menteeId: 'app-503',
    menteeName: 'Bianca Meyer',
    ventureName: 'Kraai-Med Delivery & Logistics',
    sessionDate: '2025-09-14T10:30:00Z',
    topic: 'Kraai-Med Route Optimization & Scottsdene Clinic Partnerships',
    feedbackNotes: 'Discussed MoU with Scottsdene community health clinic for chronic medication dispatch. Evaluated e-bike battery lease model.',
    actionItems: [
      'Draft SLA for pharmacy chronic medication dispatch',
      'Meet with Ward 101 health committee',
    ],
    nextMeetingDate: '2025-09-21T10:30:00Z',
    status: 'COMPLETED',
    createdAt: '2025-09-14T11:30:00Z',
  },
  {
    id: 'ses-104',
    mentorId: 'team-2',
    mentorName: 'Ntsika Mokoena',
    menteeId: 'app-501',
    menteeName: 'Kaylin Fortuin',
    ventureName: 'CivicAlert Kraaifontein',
    sessionDate: '2025-09-13T16:00:00Z',
    topic: 'Full-Stack Architecture & Distributed DB Sharding',
    feedbackNotes: 'Inspected Next.js 15 route handlers and PostgreSQL migration scripts. Code quality and TypeScript safety are outstanding.',
    actionItems: [
      'Add comprehensive unit tests for offline sync queue',
      'Deploy staging instance on Vercel/Supabase',
    ],
    nextMeetingDate: '2025-09-20T16:00:00Z',
    status: 'COMPLETED',
    createdAt: '2025-09-13T17:00:00Z',
  },
  {
    id: 'ses-105',
    mentorId: 'team-3',
    mentorName: 'Liesl Brink',
    menteeId: 'app-502',
    menteeName: 'Simphiwe Mavuso',
    ventureName: 'GreenWaste PET Filament',
    sessionDate: '2025-09-15T11:00:00Z',
    topic: 'Extruder Heated Nozzle Calibration & Recycled PET Slicing',
    feedbackNotes: 'Tested shredded milk bottle PET flakes through the barrel extruder. Temperature curve needs PID tuning at 245°C.',
    actionItems: [
      'Calibrate thermistor readings on nozzle',
      'Print tensile test coupon with extruded spool',
    ],
    nextMeetingDate: '2025-09-22T11:00:00Z',
    status: 'COMPLETED',
    createdAt: '2025-09-15T12:00:00Z',
  },
];

export const SEED_BMS_CANVAS: BmsCanvas = {
  id: 'canvas-kasipay',
  businessSlug: 'kasipay',
  businessName: 'KasiPay Financial Technologies (Pty) Ltd',
  tagline: 'The Offline-First Payment Terminal for Township Spaza Retailers',
  founderId: 'mem-1',
  founderName: 'Sipho Ndlovu',
  founderEmail: 'sipho@kasipay.co.za',
  founderPhone: '+27 82 456 7890',
  industrySector: 'Fintech & Micro-Payments',
  stage: 'Pilot Phase (26 Active Retailers)',
  cipcNumber: '2024/782194/07',
  taxPin: '9823-1490-5512',
  location: 'Kraaifontein (Scottsville & Bloekombos)',
  websiteUrl: 'https://kasipay.co.za',
  assignedMentorId: 'team-4',
  assignedMentorName: 'Tariq Johnson',
  lastEdited: '2025-09-15T18:00:00Z',
  blocks: {
    KEY_PARTNERS: [
      { id: 'c-1', title: 'Local Spaza Shop Association (45 Retailers)', notes: 'Primary merchant acquisition channel in Kraaifontein', createdAt: '2025-08-01' },
      { id: 'c-2', title: 'Banking Switch Provider (Stitch / Ozow)', notes: 'Settlement rails and EFT rails API access', createdAt: '2025-08-01' },
      { id: 'c-3', title: 'The Daily Grind Hub (Incubator)', notes: 'Desk space, mentorship, and grant linkage', createdAt: '2025-08-01' },
    ],
    KEY_ACTIVITIES: [
      { id: 'c-4', title: 'Merchant Onboarding & Bluetooth Printer Provision', notes: 'Deploying low-cost rugged hardware with QR cards', createdAt: '2025-08-02' },
      { id: 'c-5', title: 'Offline Transaction Queue Sync', notes: 'Ensuring transactions buffer safely during load-shedding', createdAt: '2025-08-02' },
      { id: 'c-6', title: 'Daily Z-Report WhatsApp Delivery', notes: 'Automated revenue reconciliation sent to shop owners', createdAt: '2025-08-02' },
    ],
    VALUE_PROPOSITIONS: [
      { id: 'c-7', title: '0.8% Transaction Fee vs Bank 3.5%', notes: 'Saves R1,200/month per micro-trader on swipe fees', createdAt: '2025-08-03' },
      { id: 'c-8', title: 'Instant Next-Hour Bank Settlement', notes: 'Cash flow returned within 60 minutes for morning stock runs', createdAt: '2025-08-03' },
      { id: 'c-9', title: 'Load-Shedding Resilient Terminal', notes: 'Battery lasts 48h with Bluetooth offline receipt print', createdAt: '2025-08-03' },
    ],
    CUSTOMER_RELATIONSHIPS: [
      { id: 'c-10', title: 'Hyperlocal In-Person Agent Support', notes: 'TDGH student support crew on ground within 15 minutes', createdAt: '2025-08-04' },
      { id: 'c-11', title: 'Vernacular WhatsApp Help Desk', notes: 'Afrikaans & isiXhosa audio note troubleshooting', createdAt: '2025-08-04' },
    ],
    CUSTOMER_SEGMENTS: [
      { id: 'c-12', title: 'Township Spaza Shop Owners (Kraaifontein)', notes: 'Cash-heavy merchants needing electronic payment options', createdAt: '2025-08-05' },
      { id: 'c-13', title: 'Independent Butchery & Tavern Operators', notes: 'Higher volume daily cash handling requiring card acceptance', createdAt: '2025-08-05' },
      { id: 'c-14', title: 'Local Taxi Rank Vendors', notes: 'Mobile merchants needing lightweight wearable QR badges', createdAt: '2025-08-05' },
    ],
    KEY_RESOURCES: [
      { id: 'c-15', title: 'Proprietary Encrypted Offline Sync Engine', notes: 'Built on Next.js, IndexedDB & Supabase Edge Functions', createdAt: '2025-08-06' },
      { id: 'c-16', title: 'TDGH 3D-Printed Rugged POS Housings', notes: 'Casing printed in FabLab using impact-resistant PETG', createdAt: '2025-08-06' },
    ],
    CHANNELS: [
      { id: 'c-17', title: 'Direct Street-By-Street Field Demonstrations', notes: 'Weekly live merchant onboarding runs along 4 Midway and Scottsville', createdAt: '2025-08-07' },
      { id: 'c-18', title: 'Merchant Referral Cash Incentive (R150 per store)', notes: 'Viral growth through trusted peer recommendations', createdAt: '2025-08-07' },
    ],
    COST_STRUCTURE: [
      { id: 'c-19', title: 'Hardware Fabrication (R320 per thermal printer kit)', notes: '3D print housing + imported mini Bluetooth printer', createdAt: '2025-08-08' },
      { id: 'c-20', title: 'Payment Switch Interchange Fee (0.45%)', notes: 'Core processing and clearing cost', createdAt: '2025-08-08' },
      { id: 'c-21', title: 'Field Agent Commissions & Data Subsidies', notes: 'R4,500/mo team allocation', createdAt: '2025-08-08' },
    ],
    REVENUE_STREAMS: [
      { id: 'c-22', title: '0.8% Merchant Discount Rate (MDR)', notes: 'Generates R8,400 monthly on R1.05m processing volume', createdAt: '2025-08-09' },
      { id: 'c-23', title: 'Value-Added Services: Airtime, Electricity & Lotto', notes: '2.5% commission on prepaid municipal vouchers', createdAt: '2025-08-09' },
      { id: 'c-24', title: 'Terminal Rental Subscription (R99/mo)', notes: 'Guaranteed recurring software & hardware replacement tier', createdAt: '2025-08-09' },
    ],
  },
};

export const SEED_BMS_ROADMAP: BmsMilestone[] = [
  {
    id: 'ms-1',
    weekRange: 'Weeks 1-2',
    phaseTitle: 'Problem Identification & Customer Empathy',
    objectives: [
      'Interview 25 spaza shop owners across Scottsville and Bloekombos',
      'Document real cost of bank card machines and cash robbery risks',
      'Complete initial Lean Canvas Draft #1',
    ],
    completed: true,
    mentorApproved: true,
    assignedMentorId: 'team-4',
    assignedMentorName: 'Tariq Johnson',
    mentorDirective: 'Target merchants on 4th Avenue who were impacted by stage 4 load-shedding. Verify their average transaction size.',
    deliverableSubmitted: 'spaza_interview_transcripts_v1.pdf',
    notes: 'Exceptional interview depth. Discovered 84% of merchants lose sales during load-shedding card outages.',
  },
  {
    id: 'ms-2',
    weekRange: 'Weeks 3-4',
    phaseTitle: 'Value Proposition & Minimum Viable Product (MVP)',
    objectives: [
      'Design offline-first Web App architecture with PWA capability',
      'Fabricate 3D printer prototype casing in TDGH FabLab',
      'Deploy pilot QR terminal with 3 test merchants in Scottsville',
    ],
    completed: true,
    mentorApproved: true,
    assignedMentorId: 'team-4',
    assignedMentorName: 'Tariq Johnson',
    mentorDirective: 'Focus on Bluetooth thermal printer handshake latency under 2 seconds. Work with Kurt in the 3D lab for casing stress-tests.',
    deliverableSubmitted: 'kasipay_mvp_v0.9_demo.mp4',
    notes: 'Passed 30-day pilot test with zero lost transactions.',
  },
  {
    id: 'ms-3',
    weekRange: 'Weeks 5-6',
    phaseTitle: 'Regulatory Compliance & CIPC Formalization',
    objectives: [
      'Register (Pty) Ltd with CIPC and acquire Tax Clearance PIN',
      'Submit B-BBEE Level 1 Affidavit (Youth Owned)',
      'Review SARB National Payment System compliance requirements',
    ],
    completed: true,
    mentorApproved: true,
    assignedMentorId: 'team-4',
    assignedMentorName: 'Tariq Johnson',
    mentorDirective: 'Ensure bank confirmation letter matches CIPC registered legal trade name exactly to prevent switch settlement delays.',
    deliverableSubmitted: 'cipc_and_tax_pin_kasipay.pdf',
  },
  {
    id: 'ms-4',
    weekRange: 'Weeks 7-8',
    phaseTitle: 'Unit Economics, Go-To-Market & Pricing Model',
    objectives: [
      'Establish financial model: CAC, LTV, and monthly burn rate',
      'Sign 20 prospective merchants on pre-launch commitment letters',
      'Integrate automated WhatsApp daily statements',
    ],
    completed: false,
    mentorApproved: false,
    assignedMentorId: 'team-4',
    assignedMentorName: 'Tariq Johnson',
    mentorDirective: 'Verify transaction switch fees against Ozow/Stitch tiered pricing before locking merchant 0.8% transaction fee.',
    notes: 'Currently onboarding merchants #14 through #20.',
  },
  {
    id: 'ms-5',
    weekRange: 'Weeks 9-10',
    phaseTitle: 'Investor Pitch Readiness & Demonstration Day',
    objectives: [
      'Finalize 12-slide seed investor deck with traction metrics',
      'Conduct 3 dry-run pitch rehearsals before TDGH mentor panel',
      'Present live at Kraaifontein Innovation Showcase Demo Day',
    ],
    completed: false,
    mentorApproved: false,
    assignedMentorId: 'team-4',
    assignedMentorName: 'Tariq Johnson',
    mentorDirective: 'Include live demo on stage with POS offline sync. We will schedule dry-run rehearsals in the main board room.',
  },
];

export const SEED_BMS_KPIS: BmsKpis = {
  cashOnHandZar: 114000,
  monthlyBurnZar: 18500,
  runwayMonths: 6.2,
  monthlyRecurringRevenueZar: 12400,
  customerAcquisitionCostZar: 320,
  totalCustomers: 26,
  teamSize: 3,
  accountingProvider: 'SAGE',
  accountingPortalUrl: 'https://accounting.sageone.co.za',
  lastAccountingSync: '2025-09-16T10:45:00Z',
  sarsVatRegistered: true,
  bankAccountName: 'First National Bank - Business Cheque (Acc #62819482910)',
  reconciledLedgerBalanceZar: 114000,
  accountsReceivableZar: 12600,
  accountsPayableZar: 8400,
};

export const SEED_BMS_DOCS: BmsDocument[] = [
  {
    id: 'doc-1',
    title: 'CIPC Certificate of Incorporation (KasiPay Technologies Pty Ltd)',
    type: 'CIPC_REGISTRATION',
    status: 'VERIFIED',
    filename: 'KasiPay_CIPC_Registration_2025.pdf',
    fileSize: '420 KB',
    uploadedAt: '2025-07-14',
  },
  {
    id: 'doc-2',
    title: 'B-BBEE Qualifying Small Enterprise Affidavit (Level 1, 100% Black Youth Owned)',
    type: 'BBBEE_AFFIDAVIT',
    status: 'VERIFIED',
    filename: 'BBBEE_Affidavit_Commissioner_Signed.pdf',
    fileSize: '680 KB',
    uploadedAt: '2025-07-20',
    expiryDate: '2026-07-19',
  },
  {
    id: 'doc-3',
    title: 'SARS Good Standing Tax Clearance Certificate',
    type: 'TAX_PIN_SARS',
    status: 'VERIFIED',
    filename: 'SARS_Tax_Clearance_Pin_2025.pdf',
    fileSize: '290 KB',
    uploadedAt: '2025-08-01',
    expiryDate: '2026-08-01',
  },
  {
    id: 'doc-4',
    title: 'Seed Investor Pitch Deck (Series Pre-Seed R500k)',
    type: 'INVESTOR_PITCH_DECK',
    status: 'PENDING_REVIEW',
    filename: 'KasiPay_Pitch_Deck_August2025_v4.pdf',
    fileSize: '3.8 MB',
    uploadedAt: '2025-09-02',
  },
];
